### ISSUE TITLE
Unsure what to replace in the redback_inverter_mode.yaml

### ISSUE THREAD

**Issue by LachyGoshi** [cabberley/Home-Assistant_Redback_Invertor_Mode_Set#1]
Thanks again,

just trying to work this out, as I have two inverters using Juices integration. I'm wanting to set this up to the SH 5000 hybrid inverter with the battery.

it shows in Home assistant integrations as RB SH5000 but all entities are named:
sensor.rb_sh5000_grid_frequency
for example, so what exactly do i change the two lines in your yaml to be?
is it this?
          serialNumber: "{{ state_attr( \"sensor.rb_sh5000_inverter_status\",\"serial_number\") }}"
          swVersion: "{{ state_attr( \"sensor.rb_sh5000_inverter_status\",\"software_version\") }}"
i dont have any sensor for inverter status currently.

**Comment by LachyGoshi** [comment]
i have also tried:

serialNumber: "RB23456789"
swVersion: "2.18.32305.2"


and with single quotes:
serialNumber: 'RB123456789'
swVersion: '2.18.32305.2'

**Comment by LachyGoshi** [comment]
I have also noticed that installing pyscript via hacs, it creates a pyscript folder at /config/custom_components/pyscript/

which looks normal when comparing to all other integrations I have added via hacs,

however, there is also a pyscript folder created directly in the config folder at /config/pyscript/

which one should I be copying your scripts to?

**Comment by LachyGoshi** [comment]
OK - ignore this for now, looks like i got it working (although had to hard code my serial number and software version in to the files as could not work out how to utilize the existing redback integration from Juice.

i will try and provide feedback to the process next week - there was alot of details different such as file locations and additional front end card things to install.

Amazing to have this control! thanks so much.

**Comment by cabberley** [comment]
Thanks
Sorry the difficulties you had with the serial and sw version sensors is due to my enhancements to juices code. Those sensors come from that integration, part of the updates I have pending for merging into that.
Sometime when I get enough time and in the coding mood, I will probably rewrite/merge everything into a single integration. I need to catchup with a friend I have at redback and ask again if they will expose via the api the inverter control.
Also atm, redback doesn't expose to customers the inverter modes that do curtailment, they are there in the inverter which is actually a GoodWe, they just have chosen in their product not to enable customers to use them.

**Comment by cabberley** [comment]
> I have also noticed that installing pyscript via hacs, it creates a pyscript folder at /config/custom_components/pyscript/
> 
> 
> 
> which looks normal when comparing to all other integrations I have added via hacs,
> 
> 
> 
> however, there is also a pyscript folder created directly in the config folder at /config/pyscript/
> 
> 
> 
> which one should I be copying your scripts to?
> 
> 

So the HACS custom folder is where pyscript stores its code to enable Python scripts, the config/pyscripts folder is where you store scripts you create and want to run I.e this code.

**Comment by raeffer** [comment]
Wow I have wasted hours trying to get this to work. Thought it was my crap novice computer skills. I did find a typo in the secrets file with the use of 'redpack_password' instead of 'redback_password' but despite my enthusiasm fixing it didnt help.

@LachyGoshi any help would be greatly appreciated!
@cabberley this thread might be of interest to you also

https://community.home-assistant.io/t/syntax-error-creating-rest-sensor-from-api-call/470809?u=raeffer

**Comment by raeffer** [comment]
Sorry that last response doesn't read how intended. I meant like WOW I have finally figured out why it wasn't working and it wasn't me. I just wanted @cabberley to get a thankyou for the his work.

**Comment by cabberley** [comment]
Sorry for the typo in the secrets file. I have fixed that.

**Comment by cabberley** [comment]
It is been a while, looks like about 12 months since I touched this stuff. But did fork juices code and run my customised version which never got merged by Juice.
You might find that helpful as well. The readme o wrote here may have been on the assumption he would merge the code I started a pull request for.

**Comment by raeffer** [comment]
Sorry I am an idiot. I am not sure what that all means. I am not a programmer.
I am really keen to get this functionality working though. I have installed everything as per your read me ....the only bit I am not sure about is the what to replace in the redback_inverter_mode.yaml. But from your previous response 'Sorry the difficulties you had with the serial and sw version sensors is due to my enhancements to juices code. Those sensors come from that integration, part of the updates I have pending for merging into that.' Do we have to do something different now?

**Comment by LachyGoshi** [comment]
Yeah I remember I spent a bit of time copying and pasting serial numbers and stuff into various sections.

I'll have a look at my files over the weekend and let you know of I can reverse engineer what I actually did to get it working. To be honest, once I got it working I haven't had to touch it. I have even upgraded my home assistance from RPI to virtual and all o had to do after restoring my backup was re authorise the integration and log back in. No issues at all.

Will report back next week.

**Comment by raeffer** [comment]
@LachyGoshi That is awesome! Thanks so much.

**Comment by raeffer** [comment]
Not sure this helps in diagnostics but I am getting this error,

Logger: custom_components.pyscript.file.redback_inverter_service
Source: custom_components/pyscript/global_ctx.py:341
integration: Pyscript Python scripting (documentation, issues)
First occurred: 8:26:44 AM (2 occurrences)
Last logged: 8:32:04 AM

Exception in </config/pyscript/redback_inverter_service.py> line 1: import redback_function ^ ModuleNotFoundError: No module named 'redback_function'

But I have copied the modules folder and the redback_function script to my psyscript folder as seen in screenshot 
![redbackFunction](https://github.com/cabberley/Home-Assistant_Redback_Invertor_Mode_Set/assets/168394856/d9346c08-d362-4439-b8da-15b656045240)

**Comment by LachyGoshi** [comment]
ok, had a quick look through my config files and the readme's for both Juices integration (https://github.com/juicejuice/homeassistant_redback) and Chriss' Inverter Mode Set  integration (https://github.com/cabberley/Home-Assistant_Redback_Invertor_Mode_Set) as well as the Pyscript pages (https://hacs-pyscript.readthedocs.io/en/stable/). I also had to install the layout card (https://github.com/thomasloven/lovelace-layout-card) as from memory, the example Chris gives for a card also relies on this layout card to be installed.... I think i remember having everything actually working sooner but just the display wasn't working until I installed this lovelace card.

essentially, Chris has a number of changes to juices integration that Juice has not merged in yet - ( @cabberley let me know if i can help get this done - i have a single phase SH5000 hybrid system. ) - and because these changes are not in juices integration, I had to manually hard code a few parameters such as serial number, swVersion and ROSS Version etc and while troubleshooting i removed the secretes file and just put login details in directly.

I replaced my actual serial number with RB00000000000000 for privacy.

Here is what i have in my: /homeassistant/configuration.yaml

```
homeassistant:
  packages:
    redback_inverter_mode: !include /config/packages/redback_inverter_mode/redback_inverter_mode.yaml

python_script:
```

in my: /homeassistant/packages/redback_inverter_mode.yaml
note that i didnt have success using secrets so had email and password in this file directly.

```
#Create entities to setup Redback Inverter mode
input_number:
  redback_inverter_power_setting_w:
    name: 'Redback Inverter Power Set Watts'
    unit_of_measurement: W
    icon: mdi:home-lightning-bolt-outline
    initial: 0
    min: 0
    max: 10000
    step: 100
    mode: box
input_select:
  redback_inverter_mode_setting:
    name: Redback Inverter Mode Select
    options:
      - Auto
      - Charge Battery
      - Discharge Battery
      - Import Power
      - Export Power
      - Conserve
    initial: Auto
    icon: mdi:transmission-tower
input_button:
  redback_inverter_set_mode:
    name: 'Redback Inverter Mode Set'
    icon: mdi:solar-power-variant
script:
  redback_inverter_mode_update:
    alias: Redback Inverter Mode Update
    sequence:
      - service: pyscript.set_invertor_mode
        data:
          email: 'email@domain.com'
          password: 'password'
          serialNumber: "RB00000000000000"
          swVersion: "2.18.32305.2"
          inverterMode: "{{ states( \"input_select.redback_inverter_mode_Setting\") | replace(\" \",\"\") }}"
          inverterPower: "{{ states( \"input_number.redback_inverter_power_setting_w\") | int }}"
    mode: queued
    max: 2
```
    
as is a common theme you will see with me, i was unsure of exact folder structure, so i also created a sub directory /homeassistant/packages/redback_inverter_mode/ where i had the same detail:

in my: /homeassistant/packages/redback_inverter_mode/redback_inverter_mode.yaml
```
#Create entities to setup Redback Inverter mode
input_number:
  redback_inverter_power_setting_w:
    name: 'Redback Inverter Power Set Watts'
    unit_of_measurement: W
    icon: mdi:home-lightning-bolt-outline
    initial: 0
    min: 0
    max: 10000
    step: 100
    mode: box
input_select:
  redback_inverter_mode_setting:
    name: Redback Inverter Mode Select
    options:
      - Auto
      - Charge Battery
      - Discharge Battery
      - Import Power
      - Export Power
      - Conserve
    initial: Auto
    icon: mdi:transmission-tower
input_button:
  redback_inverter_set_mode:
    name: 'Redback Inverter Mode Set'
    icon: mdi:solar-power-variant
script:
  redback_inverter_mode_update:
    alias: Redback Inverter Mode Update
    sequence:
      - service: pyscript.set_invertor_mode
        data:
          email: 'email@domain.com'
          password: 'password'
          serialNumber: 'RB00000000000000'
          swVersion: '2.18.32305.2'
          inverterMode: "{{ states( \"input_select.redback_inverter_mode_Setting\") | replace(\" \",\"\") }}"
          inverterPower: "{{ states( \"input_number.redback_inverter_power_setting_w\") | int }}"
    mode: queued
    max: 2
```
    
Only just now I am noting that the serial number and login details are within 'single' quotations unlike the file above in "double" quotations. I don't know if there is any logical difference.


in my: /homeassistant/pyscript/redback_inverter_service.py

```
import redback_function

@service
def set_invertor_mode(email,password, serialNumber, inverterMode, inverterPower, swVersion):
    if email =='secret':
        email = pyscript.config['secrets']['redback_email']
    if password =='secret':
        password = pyscript.config['secrets']['redback_password']
    if email =='' or password =='' or serialNumber =='' or inverterMode =='' or swVersion =='':
        return 'Error: Missing parameter'
    setInverter = redback_function.setInverterMode(rbEmail= email, rbPassword=password, rbSerialNumber='RB00000000000000', rbInverterMode=inverterMode, rbInverterPower=inverterPower, rbRossVersion='2.18.32305.2')
```
Now I still dont know on the exact file / folder structure required, so in
/homeassistant/pyscript/modules/
i have copies of the .py scripts, but also created a sub directory
/homeassistant/pyscript/modules/redback_inverter_mode/
that has the same .py script files. I don't know which location the integration actually calls but this double up structure works for me so I've left it. (side note, i had originally had all these .py script files in /homeassistant/custom_components/pyscript/modules/redback_inverter_mode/ but @cabberley confirmed above that this is the WRONG location for them as the custom_components is just for the pyscipt integration an not any sub scripts that is uses).
I have copies of all my scripts below.

in my: /homeassistant/pyscript/modules/redback_function.py

```
from bs4 import BeautifulSoup
import requests
import requests_oauthlib

@pyscript_executor

def setInverterMode(rbEmail, rbPassword, rbSerialNumber,  rbInverterMode,  rbInverterPower, rbRossVersion):
    loginUrl = "https://portal.redbacktech.com/Account/Login"
    configureurl = 'https://portal.redbacktech.com/productcontrol/Configure?serialNumber=RB00000000000000'
    inverterSetUrl = 'https://portal.redbacktech.com/productcontrol/Index'
    s = requests.Session()
    redbackLogin = s.get(loginUrl)
    soup = BeautifulSoup(redbackLogin.content , features="html.parser")
    form = soup.find("form", class_="login-form")
    hidden_input = form.find("input", type="hidden")
    globalAntiForgeryToken = hidden_input.attrs['value']
    redbackReq = s.post(loginUrl, data={"Email": rbEmail, "Password": rbPassword,"__RequestVerificationToken": globalAntiForgeryToken})
    redbackReq.raise_for_status()
    redbackSetInverter = s.get(configureurl)
    redbackSetInverter.raise_for_status()
    soup = BeautifulSoup(redbackSetInverter.content , features='html.parser')
    globalAntiForgeryToken = soup.find('form', id='GlobalAntiForgeryToken')
    hidden_input = globalAntiForgeryToken.find("input", type="hidden")
    globalAntiForgeryToken = hidden_input.attrs['value']
    inverterOperationType='Set'
    headers = {'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Referer': 'https://portal.redbacktech.com/productcontrol/Configure?serialNumber=' + rbSerialNumber}
    body = {'SerialNumber': rbSerialNumber,'AppliedTariffId':'','InverterOperation[Type]':inverterOperationType,'InverterOperation[Mode]':rbInverterMode, 'InverterOperation[PowerInWatts]':rbInverterPower, 'InverterOperation[AppliedTarrifId]':'','ProductModelName': '','RossVersion':rbRossVersion,'__RequestVerificationToken': globalAntiForgeryToken} 
    redbackSetInverter = s.post(inverterSetUrl, data = body,headers = headers)
    redbackSetInverter.raise_for_status()
    return redbackSetInverter.text
```
now I wasnt exactly sure on the folder and file structure in Pyscript, so I also have another sub directory with 

/homeassistant/pyscript/modules/redback_inverter_mode/redback_function.py

```
from bs4 import BeautifulSoup
import requests
import requests_oauthlib

@pyscript_executor

def setInverterMode(rbEmail, rbPassword, rbSerialNumber,  rbInverterMode,  rbInverterPower, rbRossVersion):
    loginUrl = "https://portal.redbacktech.com/Account/Login"
    configureurl = 'https://portal.redbacktech.com/productcontrol/Configure?serialNumber=RB00000000000000'
    inverterSetUrl = 'https://portal.redbacktech.com/productcontrol/Index'
    s = requests.Session()
    redbackLogin = s.get(loginUrl)
    soup = BeautifulSoup(redbackLogin.content , features="html.parser")
    form = soup.find("form", class_="login-form")
    hidden_input = form.find("input", type="hidden")
    globalAntiForgeryToken = hidden_input.attrs['value']
    redbackReq = s.post(loginUrl, data={"Email": rbEmail, "Password": rbPassword,"__RequestVerificationToken": globalAntiForgeryToken})
    redbackReq.raise_for_status()
    redbackSetInverter = s.get(configureurl)
    redbackSetInverter.raise_for_status()
    soup = BeautifulSoup(redbackSetInverter.content , features='html.parser')
    globalAntiForgeryToken = soup.find('form', id='GlobalAntiForgeryToken')
    hidden_input = globalAntiForgeryToken.find("input", type="hidden")
    globalAntiForgeryToken = hidden_input.attrs['value']
    inverterOperationType='Set'
    headers = {'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Referer': 'https://portal.redbacktech.com/productcontrol/Configure?serialNumber=' + rbSerialNumber}
    body = {'SerialNumber': rbSerialNumber,'AppliedTariffId':'','InverterOperation[Type]':inverterOperationType,'InverterOperation[Mode]':rbInverterMode, 'InverterOperation[PowerInWatts]':rbInverterPower, 'InverterOperation[AppliedTarrifId]':'','ProductModelName': '','RossVersion':rbRossVersion,'__RequestVerificationToken': globalAntiForgeryToken} 
    redbackSetInverter = s.post(inverterSetUrl, data = body,headers = headers)
    redbackSetInverter.raise_for_status()
    return redbackSetInverter.text)
```
So as you can see its the same script file as the redback_function.py in the folder above.

Hopefully this helps, and if you have Juices integration working, then get pyscript installed and running (i use the GUI once its installed to Allow All Imports and Access hass as a global variable), then have your files in configuration.yaml and /homeassistant/pyscript and /homeassistant/packages/ directories as i have shared above, yours should also work. I used no secret files and manually entered login details, serial number, swVersion and ROSS version and i doubled up everywhere in Packages and Pyscript. Maybe now Chis may be able to confirm exact locations that are required.... its all new to me and i haven't touched it since i got it working.

That's about all I can offer as i am definitely no coder or programmer.

I think it would be easier if Juice approved Chris' Pull request from July last year and then a lot of the name mapping would be simpler... in a perfect world, both integrations would be merged in to a single one.... I'm happy to help test what ever is needed, I have an SI5000 straight inverter, and a SH5000 single phase hybrid with 20kwh of batteries.

Good luck, let us know how you go @raeffer

**Comment by raeffer** [comment]
I am so close! I can now see the functionality in my desktop but...
![image](https://github.com/cabberley/Home-Assistant_Redback_Invertor_Mode_Set/assets/168394856/26ce88dd-9d8d-4751-9a3e-2edf54af09e3)

It seems I dont have the two sensors at the top even though I have the juice integration installed via HACS and working??

Also if i change the mode in the drop down in the GUI then push the button below it I get this error

Service pyscript.set_invertor_mode called service script.redback_inverter_mode_update which was not found.

**Comment by raeffer** [comment]
I have a ST10000 inverter by the way.

Also thankyou so much for making the effort to help @LachyGoshi

**Comment by cabberley** [comment]
@raeffer in the code in this report, you will find a packages folder which you can either follow HA packages methodology or copy them into configuration.yml. They create the two "helpers" and the automation scripts to tell the redback to change its mode.

**Comment by cabberley** [comment]
They I am pretty sure are 2 additional sensors in my forked repo that never got merged into juices. If you look in sensors.py you will find them in there. https://github.com/cabberley/homeassistant_redback

**Comment by raeffer** [comment]
Ok i can see your sensors.py file but what do i di with it? sorry... do i copy it into the pyscript folder? or do i take out the two sensor entries and put them in my config.yaml under pyscipt:

**Comment by LachyGoshi** [comment]
Its the same for me, those 2 have never worked as I have the standard juice integration also. Glad you got it working though!

**Comment by raeffer** [comment]
Cheers @LachyGoshi for the help. Unfortunately it isn't working for me and i am not smart enough...yet... to figure it out.

When I try and use it I get this error...

Service pyscript.set_invertor_mode called service script.redback_inverter_mode_update which was not found.

**Comment by LachyGoshi** [comment]
So I looked in my settings -> scripts and there is one there.

See attached screen shots.

It's not editable in the GUI as it's not a script in the scripts.yaml file, but I can't actually find where this is (have browsed around using file editer)

But I can read it from the GUI:

```
service: pyscript.set_invertor_mode
data:
  email: email@domain.com
  password: passwors
  serialNumber: RB00000000000000
  swVersion: 2.18.32305.2
  inverterMode: >-
    {{ states( "input_select.redback_inverter_mode_Setting") | replace(" ","")
    }}
  inverterPower: "{{ states( \"input_number.redback_inverter_power_setting_w\") | int }}"
```
Again, this has hard coded my login details, serial number, and swVersion.

If you find where this script is, then you should be in business.
![Screenshot_20240521-182423](https://github.com/cabberley/Home-Assistant_Redback_Invertor_Mode_Set/assets/60020083/2f4c0b55-11a9-4979-8044-38ee0160c543)
![Screenshot_20240521-182506](https://github.com/cabberley/Home-Assistant_Redback_Invertor_Mode_Set/assets/60020083/5197df3a-1617-480b-85a8-09ab11e0cf9b)
